version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - mosquitto-data:/mosquitto/data
      - ./mosquitto:/mosquitto/config:rw
      - mosquitto-log:/mosquitto/log

volumes:
  mosquitto-data:
  mosquitto-config:
  mosquitto-log:
